version: 'v1'
services:
  app:
    image: app
    ports:
      - "8050:8050"
    depends_on:
      - redis

  app2:
      image: app2
      ports:
        - "8051:8051"
        - "3002:3002/udp"
      depends_on:
        - redis  
     
  redis:
      image: redis:7.2.4-alpine
      ports:
        - 6379:6379
      

   
